id: I09057B09
legacy_id: P004419
ocr_import_info:
  bdrc_scan_id: W8621
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T20:17:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:23:36.337206+00:00'
last_modified: 2022-09-04 11:23:54.005274
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8621
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8621
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲང་ངེས་རྣམ་བཤད་བསྟན་པའི་སྒྲོན་མེ།
  author: གཉལ་སྟོན་དཔལ་འབྱོར་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.7121773597666308
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG942:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG942
      total_pages: 584
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG942.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7121773597666308
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
