id: P004419
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:19:55.979562
source_metadata:
  id: bdr:W8621
  title: དྲང་ངེས་རྣམ་བཤད་བསྟན་པའི་སྒྲོན་མེ
  author: ''
  volumes:
    de96f3c248b9499385bb80ebcb888081:
      image_group_id: I1KG942
      title: ''
      volume_number: 1
      total_pages: 584
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
